const products = [
  {
    _id: '1',
    name: 'Paolo Sebastian 3 Pack – Premium Bandannas',
    image: '/images/Image13.png',
    description:
      'Reactive Dyeing according to International Standard.Combed Yarn Jersey 100% Cotton.Screen Printed.Rib 1×1.',
    color: 'Blue',
    category: 'Boys',
    fabric: 'Combed Yarn Jersey 100% Cotton',
    price: 89.99,
    countInStock: 10,
    rating: 4.5,
    numReviews: 12,
  },
  {
    _id: '2',
    name: 'Face Mask – My Country Dreaming',
    image: '/images/imageedit_5_7649419625.png',
    description:
      '100% Cotton with Machine Washable Short-sleeve classic tee featuring ribbed crew neckline. Pre-shrunk for fit 4.5-ounce ring-spun cotton Either tagless or with easily removed tearaway tag for comfort',
    color: 'black',
    category: 'Girls',
    fabric: 'Combed Yarn Jersey 100% Cotton',
    price: 105.99,
    countInStock: 7,
    rating: 4.0,
    numReviews: 8,
  },
  {
    _id: '3',
    name: 'Rabbit Blue Shirt',
    image: '/images/Blue-shirt-rabbit.jpg',
    description:
      '100% Cotton with Machine Washable Short-sleeve classic tee featuring ribbed crew neckline. Pre-shrunk for fit 4.5-ounce ring-spun cotton Either tagless or with easily removed tearaway tag for comfort',
    color: 'blue',
    category: 'Boys',
    fabric: 'Combed Yarn Jersey 100% Cotton',
    price: 100.99,
    countInStock: 25,
    rating: 4.5,
    numReviews: 16,
  },
  {
    _id: '4',
    name: 'Cherries Pink Shirt',
    image: '/images/cherries-shirt.jpg',
    description:
      '100% Cotton with Machine Washable Short-sleeve classic tee featuring ribbed crew neckline. Pre-shrunk for fit 4.5-ounce ring-spun cotton Either tagless or with easily removed tearaway tag for comfort',
    color: 'pink',
    category: 'Girls',
    fabric: 'Combed Yarn Jersey 100% Cotton',
    price: 70.99,
    countInStock: 15,
    rating: 4,
    numReviews: 4,
  },
  {
    _id: '5',
    name: 'Cycle Red Shirt',
    image: '/images/Red-shirt-cycle.jpg',
    description:
      '100% Cotton with Machine Washable Short-sleeve classic tee featuring ribbed crew neckline. Pre-shrunk for fit 4.5-ounce ring-spun cotton Either tagless or with easily removed tearaway tag for comfort',
    color: 'red',
    category: 'Girls',
    fabric: 'Combed Yarn Jersey 100% Cotton',
    price: 49.99,
    countInStock: 2,
    rating: 3.5,
    numReviews: 10,
  },
  {
    _id: '6',
    name: 'Listen Green Shirt',
    image: '/images/Green-Shirt-Headphone.jpg',
    description:
      '100% Cotton with Machine Washable Short-sleeve classic tee featuring ribbed crew neckline. Pre-shrunk for fit 4.5-ounce ring-spun cotton Either tagless or with easily removed tearaway tag for comfort',
    color: 'green',
    category: 'Boys',
    fabric: 'Combed Yarn Jersey 100% Cotton',
    price: 29.99,
    countInStock: 0,
    rating: 4,
    numReviews: 12,
  },
];

export default products;
